name: Build Native Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: windows-latest
            name: windows
          - os: macos-latest
            name: macos

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.1

      - name: Set up JDK
        uses: actions/setup-java@v5.1.0
        with:
          distribution: temurin
          java-version: 25

      - name: Verify Java version
        run: java -version

      - name: Set up Maven cache
        uses: actions/cache@v5.0.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and package with Maven
        run: |
          mvn -B clean package
          mvn -B org.panteleyev:jpackage-maven-plugin:1.7.4:jpackage -pl app

      - name: Upload artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: jemu-${{ matrix.name }}-${{ runner.arch }}
          path: target/dist/